"""empty message

Revision ID: 79d9beb7ce15
Revises: ae4043b6cb30
Create Date: 2026-05-12 17:52:14.870049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d9beb7ce15'
down_revision = 'ae4043b6cb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game_tier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game_tier', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
